### PR TITLE
[W-9393925, W-9495251] New date fields on application

### PR DESCRIPTION
**Pull request by vmarasow**
# Changes
## New Fields on the Application Object
To make it easy for you to track the date when an applicant is able to submit an application and the date by which they must submit one, we added the Open Date and Due Date fields to the Application object.

# Issues Closed
[W-9393925](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000NwjVYAS/view) - EDA
[W-9384949](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Nt64YAC/view) - R&A

# New Metadata
## Fields
- Application -> Open Date
- Application -> Due Date

# Changed Metadata
## Layout
- EDA Application Layout

# Testing Notes

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
Initial PR #1821

**Review by MatthewBlanski — APPROVED** [review]

**Review by RadSFDeveloper — APPROVED** [review]
Looks good to me.

**Review by juliesnow — APPROVED** [review]
Updated Changes text and approve labels/descriptions.

**Comment by spinkelman** [comment]
QA from both AC and EDA pass. Merging

**Pull request merged**
