### PR TITLE
Feature/api versioning

### PR DESCRIPTION
**Pull request by jofsky**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by jofsky** [comment]
@davisagli this was my concern, just wanted a way for the team to not hard code 256 files. But i understand.

**Comment by lifewithryan** [comment]
@jofsky @davisagli I think all we really do is global search/replace in our IDEs anyway. So this is appreciated but perhaps overhead and if there are concerns in other areas, we should probably just move on. One of our devs did notice however that once we run that flow, it seemed to persist the API numbers to disk anyway, so its probably not quite read for prime time as if this is something we were going to do, it shouldn't persist, it should modify in transit.
I think we can close this perhaps?

**Comment by jofsky** [comment]
Thanks for the discussion @davisagli @lifewithryan sorry for wasting your time. @davisagli can I work on moving the Find replace task to CCI I know we had discussed the possibility of you creating one, wanted to check to see where you were at on that/if I could help.

**Comment by davisagli** [comment]
@jofsky please look at the existing FindReplace task https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/tasks/util.py#L125 and create a github issue or work item describing what changes you'd like to make to it.

**Pull request closed without merging**
