### PR TITLE
Adding EDA list views, layouts, FLS, and other metadata preferences from 1.79 feature testing

### PR DESCRIPTION
**Pull request by dgamboni**
_Summary_ : Adding EDA list views, fields to page layouts, FLS, and other metadata preferences from 1.79 feature testing to qa and regression flows.

_Details_ : In order to automate setup for feature and regression testing, we periodically add metadata changes to cci flows and tasks. As our feature set has grown, we'd now like to add additional changes to the following flows / tasks:
 

- flows : **regression_org** 
- tasks: **deploy_qa_config**

### CODE REVIEW

**Comment by dgamboni** [comment]
Hi @jstvz -- These are just changes for cci tasks and I believe they should *not* be merged into master. Thanks for your help!

**Comment by jstvz** [comment]
Nice, @dgamboni. 

We will want to merge these into master, so that part is fine. Because `retrieve_changes` is pretty greedy as to what it pulls down, I'm going to make some changes to this branch and mention you here when I finish so that you can re-run and verify that I've captured all the changes you intended to make. If you have a list of the changes you made, it'll be a bit easier to remove the extraneous metadata, but no worries if you didn't, I'll figure it out.

**Comment by dgamboni** [comment]
Hi @jstvz -- As per our discussion, add following EDA Settings to "execute_qa_apex" task : 

EDA Settings > Program Plans > Enable "Validate Program Plan for Nested Plan Requirements" checkbox

EDA Settings > Affiliations > Enable "Specify Role for Created Affiliations" checkbox
EDA Settings > Affiliations > Enable "Copy Affiliation End Date from Program Enrollment:" and "Copy Affiliation Start Date from Program Enrollment:" checkboxes

Thank you!!

**Comment by jstvz** [comment]
@dgamboni Would you review when you get the chance? I inadvertently rebased this branch so you may have to do a reset (ping me if you have a question).

**Comment by ceiroa** [comment]
Hey @dgamboni, I don't think we have a WI related to this PR. Let me know and I create one to track this work (and hopefully help prioritize it against everything else in your queue). Thanks!

**Comment by dgamboni** [comment]
Hi @jstvz Should we meet up to go over these changes, or will we scrap it and do a new PR with less greedy customizations?

**Comment by jstvz** [comment]
@dgamboni I'm inclined to scrap it unless this PR includes significant config that you're not capturing in the new PR. If that's the case, we should block off a half-hour or so to go through this PR and clean it up.

**Comment by dgamboni** [comment]
> @dgamboni I'm inclined to scrap it unless this PR includes significant config that you're not capturing in the new PR. If that's the case, we should block off a half-hour or so to go through this PR and clean it up.

@jstvz No problem, go ahead and scrap it and I'll create a new PR when I'm done with the new org changes. Thanks!

**Pull request closed without merging**
