### PR TITLE
Create CCI Deploy_QA_Config Task - Adds Fields & Related Lists to Page Layouts and Creates List Views for Accounts & Contacts

### PR DESCRIPTION
**Pull request by dgamboni**
Create CCI Task Adding Fields & Related Lists to Page Layouts and Creating List Views for Accounts & Contacts

# Changes
In order to lessen set-up time for EDA testing, we'd like to add some custom Page Layout and List View configurations in an automated cci task.

We currently have a **qa_org** flow, which is almost exactly the same as the **dev_org** flow, except that the sub-flow contained within it is called **config_qa** rather than**config_dev** flow. Note that the **config_qa** flow and the **config_dev** flows currently contain the exact same tasks. 

I believe we need to create an additional **deploy_qa_config** task with the below suggested changes, and add it to the **config_qa** sub-flow, so that QE's can then run the **qa_org** flow and get both the dev configurations plus the custom QE configurations. 

Question : Is it possible to have this task install the configurations if I was testing in a namespaced scratch org?

# Files Containing New Metadata

new file:   unpackaged/config/qa/layouts/Account-___NAMESPACE___HEDA Organization Layout.layout

new file:   unpackaged/config/qa/layouts/Contact-___NAMESPACE___HEDA Contact Layout.layout
	
new file:   unpackaged/config/qa/layouts/___NAMESPACE___Course_Enrollment__c-___NAMESPACE___HEDA Course Enrollment Layout.layout

new file:   unpackaged/config/qa/layouts/___NAMESPACE___Course_Offering__c-___NAMESPACE___HEDA Course Offering Layout.layout
	
new file:   unpackaged/config/qa/layouts/___NAMESPACE___Facility__c-___NAMESPACE___HEDA Facility Layout.layout
	
new file:   unpackaged/config/qa/layouts/___NAMESPACE___Program_Enrollment__c-___NAMESPACE___HEDA Program Enrollment Layout.layout
	
new file:   unpackaged/config/qa/objects/Account.object
	
new file:   unpackaged/config/qa/objects/Contact.object
	
new file:   unpackaged/config/qa/package.xml

# Testing Notes
* Course Connection Object > Add Term Grades Related List with columns Term Grade Name, Term, Term Grade Type, Letter Grade
* Account Object > HEDA Organization Page Layout > Facilities Related List > Columns = Facility Name, Display Name, Facility Type, Capacity, Parent Facility; Sort by Display Name, Ascending
* List View for  “All Accounts” > Fields = Account Name, Account Record Type, Parent Account, Last Modified Date
* Program Enrollment Object : Page Layout : Add “Program Plan” field 
* Contact Object : Page Layout > Add “Primary Language” field to Contact Details; Add all “Primary” fields except for Primary Language under the "Primary Affiliations" section
* Course Offering Object : Page Layout > Add “Facility” field
* Facility Object : Page Layout > Add “Display Name” field

# Dev & QA Flows & SubFlows -- See Image
CCI Dev and QA Flows and SubFlows

### CODE REVIEW

**Comment by robertbwatson** [comment]
Do we need to compare this with #814?

**Comment by dgamboni** [comment]
@robertbwatson I believe that for that ticket, @jstvz took the setup info I'd documented [here](https://salesforce.quip.com/VT5WAu1W5Rxi) to create a flow for regression testing (ie, **regression_org**) to mimic testing in existing sandboxes. This ticket uses the new cci processes (see [here](https://cumulusci.readthedocs.io/en/latest/features.html#starting-a-snapshot)) to bring configuration changes directly into Github which can then be used to create (or amend) a **qa_org** flow for testing. (It's possible some of this customization would be helpful to have in the **dev_org** flow as well.)

**Comment by dgamboni** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vKOQAY" target="_blank">W-033540</a>

**Comment by ceiroa** [comment]
@dgamboni ~ I believe we agreed on Lurching issues, not pull requests. Please not that you added the Lurch command in a PR (see active tab above or URL).

**Comment by jstvz** [comment]
Okay, looks like there's some overlap between this and #814, as it includes a `deploy_qa_config` task. I propose merging this branch into that one, then @dgamboni can review/QA that.

**Comment by jstvz** [comment]
Merging in #814

**Pull request closed without merging**
