### PR TITLE
Update GEM namespace from gem0 to gem

### PR DESCRIPTION
**Pull request by bdvorachek**
# Critical Changes

# Changes
- Update Advancement Namespace default value to support the final `gem` namespace.

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes
When gem is installed and this PR is applied, all apex tests from the EDA package should pass. That part of testing is only possible after a release has been cut.

### CODE REVIEW

**Comment by bdvorachek** [comment]
**lurch: attach W-033244

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087uwbQAA" target="_blank">W-033244</a>

**Comment by bdvorachek** [comment]
Hey @robertbwatson, we're trying to get this change into the next release of EDA. Are you able to review this today?

**Comment by robertbwatson** [comment]
@ceiroa @juliesnow Do you think we actually need anything in the release notes here? Not sure if we want to have anything about this.

**Comment by robertbwatson** [comment]
> @ceiroa @juliesnow Do you think we actually need anything in the release notes here? Not sure if we want to have anything about this.

It looks like we did have release notes for this in 1.72: "Update Advancement Namespace default value to support the new gem0 namespace."

**Comment by bdvorachek** [comment]
@robertbwatson You're right, the only way to truly test this is after the beta release of EDA is cut. No, I don't believe any QE is needed from the EDA side for this.

**Comment by annejackson** [comment]
@dgamboni @juliesnow, see above comments on testing notes and what's in the changes section for release notes.  This PR has been approved by others and merged.

**Pull request merged**
