### PR TITLE
Whitespace fixes for prettier compliance

### PR DESCRIPTION
**Pull request by vmarasow**
I ran prettier locally and it found all these whitespace issues. With these changes, the prettier action turned green.
I found that my local prettier was a different version that wasn't finding these issues, so I updated prettier and found the same list of offending files as what the github action is outputting.

Feel free to merge this at your discretion. 
# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by xinnanlisf** [comment]
Hi @vmarasow, thanks for checking this out! Curious how did you update the prettier options? I ran it on my local branch and it couldn't find anything. I am wondering if the github flow is using a different option file.

**Comment by vmarasow** [comment]
I found that running `prettier -v` vs `yarn run prettier -v` returned different versions, with the `yarn run...` version being the more recent one. Try running `yarn run prettier "**/*.{html,md,yml,yaml}" -c` and see if it picks up the same changes as the github action.

**Review by MatthewBlanski — APPROVED** [review]
These changes are transparent and will fix the formatting issues checks!

**Comment by spinkelman** [comment]
QA passes. Merging

**Pull request merged**
