### PR TITLE
Lead Conversion Setting is not honoring naming convention with multiple contacts

### PR DESCRIPTION
**Pull request by mrrigney**
# Changes
- We fixed an issue that caused Lead-converted Account naming not to work as expected when you selectan existing Household Account during conversion. Now, if you select an existing Household Account when converting a Lead, the Account name changes according to EDA Settings.

# Issues Closed
[[W-9229603]](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L2U6YAK/view)

# Testing Notes

### CODE REVIEW

**Review by paulmalenke — APPROVED** [review]
👍  Looks good from my perspective.

**Review by agoolsby — APPROVED** [review]
@mrrigney Tried to provide a draft RN here too. Let me know if I hit the mark.

**Review by MatthewBlanski — APPROVED** [review]
This change is simple and elegant

**Comment by spinkelman** [comment]
QA passes. Confirmed by both Raven and myself.

**Pull request merged**
