### PR TITLE
Robot tests for Preferred Phone

### PR DESCRIPTION
**Pull request by robertbwatson**
Added Robots tests for Preferred Phone feature.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by robertbwatson** [comment]
FYI @Safiyab @Julian88Tex here is the new internal PR -- builds are running now.

**Comment by Julian88Tex** [comment]
@robertbwatson Thanks for the merge!

**Comment by robertbwatson** [comment]
> FYI @Safiyab @Julian88Tex here is the new internal PR -- builds are running now.

Builds all pass, so if we're good on your end, we can merge this. (Should I give this to Dina or someone else on the QE team to test?)

**Comment by Julian88Tex** [comment]
@robertbwatson yeah as far as I know this is good to merge outside of reviews. @Safiyab this is a new PR but I think you approved the last one so feel free to approve this one as well.

I'd also recommend adding @dgamboni as a reviewer so she can give it a test. Here is the command which should run it in a dev org: `cci task run robot --org dev -o suites robot/EDA/tests/browser/contacts/preferred_phone.robot`

**Comment by Safiyab** [comment]
@Julian88Tex The test case created as part of this PR never really ran in MetaCI. You can open the robot build and have a look at the list of tests that were run. Like I mentioned, the cases with 'unstable' tag only run when the branch is named with prefix "feature/robot".

You can rename this branch and force push your changes. But if that's too complicated, I suggest updating the tag to "stable". That way your script will run as part of "Feature Test - Robot". Does it make sense ?

**Comment by Julian88Tex** [comment]
@Safiyab Ah right yes that makes sense. @robertbwatson would you be able to update this branch name? I do not have permissions to do so.

**Comment by robertbwatson** [comment]
Closing pull request and opening a new one with the correct branch naming for Robot tests.

**Pull request closed without merging**
