### PR TITLE
W-9251641  EDA settings design updates

### PR DESCRIPTION
**Pull request by eclemmer**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Review by iskander-sfdc — APPROVED** [review]
Looks good, manual and automated tests passed

**Comment by RadSFDeveloper** [comment]
@eclemmer , where do we update EDA PRs to contain the WI reference? I do not see the reference here. Also, can we update the WI to contain the PR reference?

@iskander-sfdc , @eclemmer : I understand that prettier formatting will be resolved in another WI/PR. Can you please specify which one is that?

**Comment by eclemmer** [comment]
> @eclemmer , where do we update EDA PRs to contain the WI reference? I do not see the reference here. Also, can we update the WI to contain the PR reference?
@RadSFDeveloper [This](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000LSKvYAO/view) is the WI.  I have added the PR details there for reference.

**Comment by iskander-sfdc** [comment]
> I understand that prettier formatting will be resolved in another WI/PR. Can you please specify which one is that?

@RadSFDeveloper , afaik we don't have any WI to fix prettier atm

**Pull request merged**
