### PR TITLE
Affiliation Mappings Health Checks

### PR DESCRIPTION
**Pull request by m-kinkade**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@m-kinkade we just merged the rest of affiliation mapping HC. should we consider this PR as ready for review?

**Review by MatthewBlanski — APPROVED** [review]
It looks like we're in good shape for this! Congratulations everyone!

**Comment by xinnanlisf** [comment]
looks like this PR has other components too. Do we need to clean up them?

**Comment by rhakeshj** [comment]
QA passes and it looks good.

**Pull request merged**
