### PR TITLE
[EDA] ContentVersion trigger

### PR DESCRIPTION
**Pull request by cbunkers**
# Critical Changes

# Changes

# Issues Closed
[W-9203961](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000KXiMYAW/view)
# New Metadata

**Triggers**
- TDTM_ContentVersion.trigger

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

1. Trigger appeared with proper name and version setting in Setup > Apex Triggers and contained NO logic.
2. Triggers did not appear in a search in the Trigger Handler tab. I tested this by entering the trigger name into the Trigger Handler "All Trigger Handlers" list view

### CODE REVIEW

**Review by MatthewBlanski — APPROVED** [review]
Straight forward and good to go

**Review by paulmalenke — APPROVED** [review]
👍

**Comment by spinkelman** [comment]
QA Passes - Merging

**Comment by agoolsby** [comment]
FYI @juliesnow  - I had Chris Bunkers (an AC dev) add release notes for this 232 PR. There's no doc updates for EDA, but it will need to go into the Release Notes for 232. It's very similar to how we handled this [PR](https://github.com/SalesforceFoundation/EDA/pull/1356). Thanks.

**Comment by juliesnow** [comment]
Thanks, @agoolsby!

**Pull request merged**
