### PR TITLE
[EDA]: Allow Customers the Ability to Backfill Missing Affiliation on Existing Student Course Connection #999

### PR DESCRIPTION
**Pull request by kdy618**
# Critical Changes

# Changes
We have added a new button on EDA Settings under Course Connection tab that allows customers to backfill existing Student Course Connection with missing Affiliation.

# Issues Closed

# New Metadata
CCON_AffiliationBackfill_BATCH

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by kdy618** [comment]
To Do: 

- [ ] Create test class for the new batch class

**Comment by robertbwatson** [comment]
@kdy618 since this was merged into the parent branch, can this child branch be deleted? (If so, go ahead and click the "Delete branch" button above :))

**Comment by kdy618** [comment]
@robertbwatson, this was my mistake. When I made an update to the parent branch, it created a merge conflict PR. I tried to fix that merge conflict PR and once I did, it merged the child to the parent and that's not what I wanted. I had to revert the parent branch back to state before the child was merge to the parent. I'm probably doing something incorrectly; so I decided it might be best if I just hold off on creating a draft child PR so I don't get these merge conflict PRs until I figure out what I'm doing wrong. This has happened twice and had to revert the parent branch twice.

**Comment by robertbwatson** [comment]
@kdy618 No worries. Feel free to reach out if you'd like to walk through any of it together, if you get stuck again :)

**Comment by kdy618** [comment]
> @kdy618 No worries. Feel free to reach out if you'd like to walk through any of it together, if you get stuck again :)

definitely! Thank you so much :)

**Pull request merged**
