### PR TITLE
[W-9393925, W-9495251] New date fields on application

### PR DESCRIPTION
**Pull request by vmarasow**
# Changes
Open Date and Due Date fields have been added to the application object.

# Issues Closed
[W-9393925](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000NwjVYAS/view) - EDA
[W-9384949](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Nt64YAC/view) - R&A

# New Metadata
## Fields
- Application -> Open Date
- Application -> Due Date

# Changed Metadata
## Layout
- EDA Application Layout

# Testing Notes

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
@MatthewBlanski , @vmarasow : should this PR be merged into `feature/232.1`? We will have custom settings changed for trigger enablement next sprint 7c?

**Comment by MatthewBlanski** [comment]
> @MatthewBlanski , @vmarasow : should this PR be merged into `feature/232.1`? We will have custom settings changed for trigger enablement next sprint 7c?

It should be. 232.1. I will be branching 232.2 from it at the end of the week

**Review by MatthewBlanski — CHANGES_REQUESTED** [review]
Please generate and pull down the translation files for this PR as well.

**Comment by RadSFDeveloper** [comment]
> > @MatthewBlanski , @vmarasow : should this PR be merged into `feature/232.1`? We will have custom settings changed for trigger enablement next sprint 7c?
> 
> It should be. 232.1. I will be branching 232.2 from it at the end of the week

ok, if it is scheduled for 232.1, then @vmarasow  can you please rename the branch (renaming will close this PR)? Thanks.

**Comment by vmarasow** [comment]
I'm closing this PR and creating a new one as it seems I branched off the wrong source.

**Pull request closed without merging**
