### PR TITLE
Added escape single quotes to a dynamic soql on  tdtm_runnable

### LINKED ISSUE #1243: Add escape single quotes to a dynamic soql on tdtm_runnable
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
Currently TDTM_Filter.cls and TDTM_Runnable.cls class execute dynamic SOQL query on a String that doesn't escape single quotes. 

* **What is the expected behavior?**
Add escapeSingleQuotes() to the dynamic queries to protect against any potential SOQL injections.

* **What is the motivation / use case for changing the behavior?**
This makes our classes more secure to any possible security threats.

### PR DESCRIPTION
**Pull request by skosgi1**
# Critical Changes

# Changes
We've added the escapeSingleQuotes method to the TDTM_Filter and TDTM_Runnable classes to protect against potential SOQL injections. You shouldn't notice any change in behavior as a result of this change.

# Issues Closed
Closes #1243 

# New Metadata

# Deleted Metadata

# Testing Notes
Testing may be accomplished by adding a filter to a Trigger Handler record. Any filter functionality still working would constitute a valid test.

### CODE REVIEW

**Comment by xinnanlisf** [comment]
@skosgi1 I am wondering if we should do as @MatthewBlanski did by escaping all string variables.

**Comment by MatthewBlanski** [comment]
> @skosgi1 I am wondering if we should do as @MatthewBlanski did by escaping all string variables.

We don't need to escape anything referenced with the ':variable' syntax as those are handled natively. Anything dynamic likely should be escaped.

**Comment by xinnanlisf** [comment]
Hi @skosgi1, instead of escaping single quote for the whole query, lets escape only objectName now :)

**Comment by skosgi1** [comment]
> Hi @skosgi1, instead of escaping single quote for the whole query, lets escape only objectName now :)

updated it @xinnanlisf Thx.

**Comment by xinnanlisf** [comment]
although, @skosgi1 do we have a github issue linked to this? Also, do we need release note?

**Comment by skosgi1** [comment]
> although, @skosgi1 do we have a github issue linked to this? Also, do we need release note?

Hmm I don't think we do, since this is internal.

**Comment by skosgi1** [comment]
@juliesnow I have not added any release notes earlier thinking it is not needed. Looks like we want that. Can you please take a look when you get a chance, thank you.

**Pull request merged**
