### PR TITLE
[EDA] New Picklists Value for Citizenship Status on Contact

### LINKED ISSUE #1438: EDA] New Picklists Value for Citizenship Status on Contact
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Add a non US specific citizenship status value on a Contact. 
* **What is the current behavior?**
Currently, the Citizenship Status provides the option to select US specific citizenship status value. 
* **What is the expected behavior?**
Citizenship Status on Contact should provide non US specific value. 
* **What is the motivation / use case for changing the behavior?**
By adding "Temporary Resident", it would help represent non US specific status of a Contact. 
* **Acceptance Criteria**
When I view or create a new Contact record, I should be able to see and select non US specific value "Temporary Resident" along with existing Citizenship Status values.

### PR DESCRIPTION
**Pull request by kdy618**
# Critical Changes

# Changes
- We've added a new picklist value, "Temporary Resident" to the "Citizenship Status" field on Contact. For new installations, the new value is automatically included. If you installed an earlier EDA release, manually add the new picklist value to the "Citizenship Status" field on Contact. For information, check out see [Add Custom Fields and Picklist Values](https://powerofus.force.com/s/article/EDA-Add-Custom-Picklist-Values).

# Issues Closed
Closed #1438
# New Metadata
New Citizenship_Status__c  picklist value:
- Temporary Resident

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Review by lianeyee — APPROVED** [review]
Thanks for pinging for a review @kdy618.

**Review by MatthewBlanski — APPROVED** [review]
This is about the most straightforward PR I have reviewed.

**Review by spinkelman — APPROVED** [review]
QA passes. Testing notes on WI. No concerns.

**Review by jofsky — APPROVED** [review]
@kdy618 Should this be in K12 too?

**Comment by MatthewBlanski** [comment]
> @kdy618 Should this be in K12 too?

@jofsky We should reference this picklist task in K-12's Trial Org flow (if necessary)

**Comment by juliesnow** [comment]
Very minor edits to description

**Comment by spinkelman** [comment]
Item complete. Merging - Closing WI

**Pull request merged**
