### PR TITLE
Incorrect Course Connection Tooltips

### LINKED ISSUE #974: Incorrect Course Connection Tooltips
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug 

* **What is the current behavior?**
The description and help texts for the following fields are inaccurate. 
- Contact's Academic Program
- Course Offering
- Affiliation
- Contact

* **What is the expected behavior?**
The description and help texts for the fields listed above should be inclusive of Student and Faculty Course Connection. 

* **What is the motivation / use case for changing the behavior?**
Accurate documentation

### PR DESCRIPTION
**Pull request by kdy618**
# Critical Changes

# Changes
## General Updates
We've updated the descriptions and help text for the following fields on Course Connection: Affiliation, Contact, Contact's Academic Program, Course Offering ID.

# Issues Closed
Closes #974

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by robertbwatson** [comment]
@kdy618 Can this be a Draft until we get both WI's finalized and ready to go? (Otherwise, for now, I'm just going to assign this to you.)

**Comment by kdy618** [comment]
@robertbwatson, I don't see the option to change this PR back to draft :/ But I did update the Contact's description and help text after @juliesnow confirmation on the quip doc. That's all the fields we need right? If so, then this is ready for review. :)

**Comment by robertbwatson** [comment]
@kdy618 I think we should also consider updating the Course Offering ID field as well. It says we are, but I don't see any changes in the PR for it.

**Comment by spinkelman** [comment]
Passes QA - Merging

**Pull request merged**
