### PR TITLE
pseudo localization as of March 1, 2019

### PR DESCRIPTION
**Pull request by kumikoiwamoto**
@MatthewBlanski  please let me know if you have enough information here, or if you have any questions. Thank you.

# Critical Changes

# Changes
Pseudo localization.  We're using German (de) files.

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes
Please see if there are any layout issues due to text expansion, or if there are any hardcoded/missed labels.  The following document explains some of the common localization issues that pseudo localization can help find: https://sites.google.com/a/salesforce.com/rdlocalization/pseudo-localization1?pli=1#TOC-Common-Localization-Issues

### CODE REVIEW

**Comment by robertbwatson** [comment]
@lifewithryan Should/can this pull request be closed?

**Comment by lifewithryan** [comment]
@kumikoiwamoto Can I close this PR or do we need to leave this open? Since its something we never planned to merge.

**Comment by lifewithryan** [comment]
Not implementing this and closing PR since it was merely a dry run test.

**Comment by robertbwatson** [comment]
@lifewithryan Can we delete the branch, too?

**Comment by lifewithryan** [comment]
> @lifewithryan Can we delete the branch, too?
> 
> edit: actually, I meant your feature/rheadley/translationTestNoMerge

yea, I thought I did :) I can delete it.

**Pull request closed without merging**
