### PR TITLE
Lead Conversion is not detecting pre-existing accounts

### PR DESCRIPTION
**Pull request by mrrigney**
# Changes
- We fixed an issue that caused Lead-converted Account naming not to work as expected when you select an existing Administrative Account during conversion. Now, if you select an existing Administrative Account when converting a Lead, the Account name doesn’t change.

# Issues Closed
[[W-9230954]](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L48nYAC/view)
[[W-9229603]](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L2U6YAK/view)

# Testing Notes

### CODE REVIEW

**Review by paulmalenke — APPROVED** [review]
👍  Good from my perspective.

**Review by agoolsby — APPROVED** [review]
@mrrigney I took a pass at drafting a release note (see the Changes area). Please review and let me know if I got it wrong. Thanks!

**Review by MatthewBlanski — APPROVED** [review]
Not only is this good, it's using a constant which gives us a lever to change rapidly if we decide we need to modify it. Thank you!

**Comment by spinkelman** [comment]
QA Passes both the AC and EDA teams. Merging

**Pull request merged**
