### PR TITLE
W-030160 - Refactor Lightning Component for Account Naming

### PR DESCRIPTION
**Pull request by xinnanlisf**
Move init() to Tab component so it is not called twice
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

### CODE REVIEW

**Comment by spinkelman** [comment]
QA passes | Merging
Closing WI

**Comment by robertbwatson** [comment]
@lifewithryan @xinnanlisf Thoughts on if this should have release notes? It's nothing the customer can "see" but it is part of their experience.

**Comment by lifewithryan** [comment]
> @lifewithryan @xinnanlisf Thoughts on if this should have release notes? It's nothing the customer can "see" but it is part of their experience.

Probably -- it at least shows that we are investing in our own platform and cleaning things up, even when they're not shiny new features, or evident to our users, etc.

**Comment by robertbwatson** [comment]
> > @lifewithryan @xinnanlisf Thoughts on if this should have release notes? It's nothing the customer can "see" but it is part of their experience.
> 
> Probably -- it at least shows that we are investing in our own platform and cleaning things up, even when they're not shiny new features, or evident to our users, etc.

Then I've added @juliesnow as a reviewer on this - with the expectation she will likely not get to this until after the new year.

**Comment by robertbwatson** [comment]
> > > @lifewithryan @xinnanlisf Thoughts on if this should have release notes? It's nothing the customer can "see" but it is part of their experience.
> > 
> > 
> > Probably -- it at least shows that we are investing in our own platform and cleaning things up, even when they're not shiny new features, or evident to our users, etc.
> 
> Then I've added @juliesnow as a reviewer on this - with the expectation she will likely not get to this until after the new year.

Pinging @juliesnow on this again -- we should review this before our push to sandboxes. I took a quick stab at editing the notes above.

**Pull request merged**
