### PR TITLE
[EDA] Add New Picklist Value on Primary Address Type Field On Contact

### LINKED ISSUE #888: Investigation: Ensure Simple Address Change Treated as Update
**Note: FOR INTERNAL USE ONLY. For support questions, please use the EDA Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Investigation

* **What is the current behavior?**
When Ensure Simple Address Change Treated as Update is enabled and an update is made to a single Address field along with a change to Primary Address Type on Contact a second Address record is created.

**Steps to reproduce:**
Note: Ensure Simple Address Change Treated as Update is enabled.

Step 1: Create a Contact with Address and set Primary Address Type = Home
Step 2: Edit Contact Address (i.e. not the Address record) as follows:
Step 2a: Update Mailing City
Step 2b: Change Primary Address Type from Home to Work
Step 3: Save

A 2nd Address record is created.

If you edit the same Contact again and only change Primary Address Type (i.e. from Work to Other) and save no new Address record is created.

* **What is the expected behavior?**

Per [EDA Documentation](https://powerofus.force.com/s/article/EDA-Add-or-Update-Addresses#simple) it doesn't seem to indicate that the Primary Address Type field is part of the Address fields on Contact. If that is the case then including a change to Primary Address Type, along with a single change to an Address field, should not trigger a new Address record to be created.

* **What is the motivation / use case for changing the behavior?**
Hub post: https://powerofus.force.com/s/feed/0D51E00004wlsL7SAI

### PR DESCRIPTION
**Pull request by kdy618**
# Critical Changes

# Changes
## New Picklist Values on Contact
We've added a new picklist value, "Vacation Residence," to the "Primary Address Type" and "Secondary Address Type" fields on Contact. With these new picklist values, the "Primary Address Type" and "Secondary Address Type" picklists on Contact are now consistent with the "Address Type" picklist on the Address object. 

For new EDA installations, the new picklist values are automatically added to Contact. If your organization has an existing EDA installation, manually add "Vacation Residence" as a new picklist value to the "Primary Address Type" field and "Secondary Address Type" field on Contact. For information, check out [Add Custom Fields and Picklist Values](https://powerofus.force.com/s/article/EDA-Add-Custom-Picklist-Values).

**Note:** We've also updated the EDA Documentation to clarify the behavior of the "Simple Address Change Treated as Update" setting in EDA Settings. For more information, see  [Add or Update Addresses](https://powerofus.force.com/s/article/EDA-Add-or-Update-Addresses).

# Issues Closed
#888 

# New Metadata
- New picklist value: "Vacation Residence"
# Deleted Metadata

# Testing Notes

- Create a new Contact and select "Primary Address Type" or "Secondary Address Type" field on Contact, and I should be able to see "Vacation Residence" as an option.  Ensure that the picklist values are in alphabetical order and that "Other" is the listed as the last value. 
- Find an existing Contact record and select "Primary Address Type" or "Secondary Address Type" field on Contact, and I should be able to see "Vacation Residence" as an option. Ensure that the picklist values are in alphabetical order and that "Other" is the listed as the last value.

### CODE REVIEW

**Comment by dgamboni** [comment]
@kdy618 Does this PR close Issue #888?

**Comment by kdy618** [comment]
> @kdy618 Does this PR close Issue #888?

Not 100%. It only address a small part. Doc update is what fully address the question in this issue. Should I still tie this issue to this PR?

**Comment by dgamboni** [comment]
> > @kdy618 Does this PR close Issue #888?
> 
> Not 100%. It only address a small part. Doc update is what fully address the question in this issue. Should I still tie this issue to this PR?

My opinion -- I think we should not close the issue if it's still open and being addressed by docs work, but we should be sure to close the issue when the docs work is done. cc @juliesnow

**Comment by kdy618** [comment]
@lifewithryan , do you mind re-reviewing? I've added the new picklist value to "Secondary Address Type" picklist field on Contact as well.

**Comment by juliesnow** [comment]
@kdy618 + @dgamboni - I've already updated the doc w/ the details we scoped out in the ladybug quip doc. I think the only other update I'll need to do is to include "Vacation Residence" to the Data Dictionary as a picklist value for Secondary Address, but pls lmk if I'm missing something (we can take offline).

**Comment by kdy618** [comment]
> @kdy618 + @dgamboni - I've already updated the doc w/ the details we scoped out in the ladybug quip doc. I think the only other update I'll need to do is to include "Vacation Residence" to the Data Dictionary as a picklist value for Secondary Address, but pls lmk if I'm missing something (we can take offline).

@juliesnow , awesome! Nope, the only change that was made today was adding the picklist value to the "Secondary Address Type" picklist field on Contact as well. @dgamboni , please let me know if I've missed anything else.

**Comment by lifewithryan** [comment]
@juliesnow @kdy618 - forgive me if this has been addressed but since we are adding these values, do we want to call out in the release notes that existing customers should/could/can add these values to their picklists?

**Comment by kdy618** [comment]
> @juliesnow @kdy618 - forgive me if this has been addressed but since we are adding these values, do we want to call out in the release notes that existing customers should/could/can add these values to their picklists?

@lifewithryan , that note should be written under the "Changes" section?

**Comment by lifewithryan** [comment]
> > @juliesnow @kdy618 - forgive me if this has been addressed but since we are adding these values, do we want to call out in the release notes that existing customers should/could/can add these values to their picklists?
> 
> @lifewithryan , that note should be written under the "Changes" section?

I believe that is where we normally have it but that is why I pinged @juliesnow :)

**Comment by dgamboni** [comment]
> @kdy618 + @dgamboni - I've already updated the doc w/ the details we scoped out in the ladybug quip doc. I think the only other update I'll need to do is to include "Vacation Residence" to the Data Dictionary as a picklist value for Secondary Address, but pls lmk if I'm missing something (we can take offline).

If I'm understanding correctly, the doc work addresses everything in #888, so I'm thinking we should go ahead and add the issue number.

**Comment by juliesnow** [comment]
Yes, @lifewithryan, we're good w/ docs. I just need to update the DD w/ the new picklist value and the release notes (as you've noted), but we have time.

**Comment by dgamboni** [comment]
Tested/ Passes QE.

**Pull request merged**
